feat!: remove packages
rollingrhinoremix/rhino-deinst pull request #22
Opened 2022-06-04 22:10 UTC by X4X5

This is something I tested in my own fork for the Unity package until something more permanent is proposed. When installing `unity`, Ubuntu will install GNOME apps by default because that is something Ubuntu does. This addition will remove GNOME apps when Unity is chosen as the desktop environment, so the user doesn't have to go through the trouble of removing the package themselves.

2022-06-04 22:17 UTC, Henryws requested changes

2022-06-04 22:17 UTC, Henryws commented on rhino-deinst
> +sudo apt remove -y ${remove_packages}
```suggestion
if [[ -n $remove_packages ]]; then
    echo "Removing unnecessary packages"
    sudo apt remove -y ${remove_packages}
fi
```

2022-06-04 22:19 UTC, X4X5 commented
I wanted to find a way to utilize `sudo apt autoremove '^gnome-shell' --purge` if none of the GNOME options were chosen, but idk the best way to implement that yet. Trying to figure it out

2022-06-07 00:22 UTC, X4X5 commented
I will reopen this PR at another time. I'm working on something to add to this PR, but I don't know if it'll work or not. I'll reopen when I am done

2022-06-07 00:22 UTC, closed without merging