feat: rhino-deinst tweaks
rollingrhinoremix/rhino-deinst pull request #24
Opened 2022-06-07 15:36 UTC by X4X5

Made some more adjustments with the tool

1. Added `remove_packages`. Within this flag, it'll remove the packages that are marked for removal, and then clean up useless packages with `sudo apt autoremove -y`.
2. Added packages to `extra_packages` to `Unity (Ubuntu)` so now MATE and Yaru packages are installed with the Unity desktop
3. Reworked how Unity gets installed, so now Unity shouldn't be installed incomplete. With that, the `Unity` only option was removed. Furthermore, Unity will now install Unity 7.6, the latest iteration of the Unity desktop by Rudra Saraswat.

2022-06-08 05:43 UTC, X4X5 commented
Please note that the 8th commit made was just to keep my fork up to date. I myself didn't add or remove anything

2022-06-08 12:20 UTC, Henryws requested changes

2022-06-08 12:20 UTC, Henryws commented on rhino-deinst
> +if [[ ${desktop[@]} = "ubuntu-unity-desktop" ]]; then
```suggestion
if [[ ${desktop[@]} == "ubuntu-unity-desktop" ]]; then
```

2022-06-13 15:33 UTC, Henryws requested changes

2022-06-13 15:33 UTC, Henryws commented on rhino-deinst
> +if false ! [[ ${desktop[@]} == "ubuntu-desktop gnome-session-flashback vanilla-gnome-desktop" ]]; then
Remove the double negative

2022-06-15 02:32 UTC, merged